name: Publish to NPM

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Allows Github OIDC to generate a verifiable security token
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Verify & Test Library
        run: |
          pnpm run build
          pnpm run test
          pnpm run lint

      - name: Publish to NPM Registry with Provenance
        run: |
          pnpm pack
          npm publish *.tgz --registry=https://npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
